### ISSUE TITLE
Crashing with iOS 9

### ISSUE THREAD

**Issue by grimabe** [larcus94/ImagePickerSheetController#26]
I installed iOS 9 on an iPhone 6 and the library is don't working anymore.
Indeed if you tab on any pictures inside the collection view to select one it crashes with the following error : 

```
2015-06-09 23:05:04.010 barter[592:608643] *** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3473.13/UICollectionViewData.m:408
2015-06-09 23:05:04.015 barter[592:608643] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'layout attributes for supplementary item at index path (<NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}) changed from <UICollectionViewLayoutAttributes: 0x135b39780> index path: (<NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}); element kind: (UICollectionElementKindSectionHeader); frame = (73 5; 29 130); hidden = YES; zIndex = 1;  to <UICollectionViewLayoutAttributes: 0x135c32f00> index path: (<NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}); element kind: (UICollectionElementKindSectionHeader); frame = (73 5; 29 233); hidden = YES; zIndex = 1;  without invalidating the layout'
*** First throw call stack:

```

However I fixed the issue in the **didSelectItemAtIndexPath** method of the library  more precisely inside the **animateWithDuration** block by adding ** layout.showsSupplementaryViews = true** between the tableview updates methods.

```
                self.setNeedsLayout()
                UIView.animateWithDuration(enlargementAnimationDuration, animations: {
                    self.tableView.beginUpdates()
                    layout.showsSupplementaryViews = true
                    self.tableView.endUpdates()
                    self.layoutIfNeeded()
                    }, completion: { finished in
                        self.reloadButtonTitles()
                        layout.showsSupplementaryViews = true
                        self.delegate?.imagePickerSheetDidEnlargePreviews?(self)
                })

```

It is maybe not a real fix because ios9 is under beta. Moreover the fixe appears to make the collectionview scrolling at the beginning so the selected picture will not be at the center of the collection view.
But it can still help someone who is facing the same issue.

**Comment by grimabe** [comment]
Because I was not using the latest version of your ImagePickerSheetController it is not exactly the lines of code in the class now. But the error is still the same and the workaround still working.

**Comment by larcus94** [comment]
Thanks for the issue. I fixed this already in the swift-2.0 branch. It isn't merged yet because it's still WIP.

**Comment by D-Wang** [comment]
I still see this problem when run the example, have you merged? 
here is the crash log:
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'layout attributes for supplementary item at index path (<NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}) changed from <UICollectionViewLayoutAttributes: 0x7f874a7708d0> index path: (<NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}); element kind: (UICollectionElementKindSectionHeader); frame = (46.7011 5; 47 119); hidden = YES; zIndex = 1;  to <UICollectionViewLayoutAttributes: 0x7f874a45f6d0> index path: (<NSIndexPath: 0xc000000000000016> {length = 2, path = 0 - 0}); element kind: (UICollectionElementKindSectionHeader); frame = (46.7011 5; 47 271); hidden = YES; zIndex = 1;  without invalidating the layout'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000109be5f65 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010b9a4deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000109be5dca +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010a02eae2 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
	4   UIKit                               0x000000010ad8cafd __45-[UICollectionViewData validateLayoutInRect:]_block_invoke + 921
...
